lablup/backend.ai-manager

- ai/backend/manager/cli/etcd.py
for fix issue #85 : Implement "--prefix" option for manager CLI's etcd command
> add args prefix in ai.backend.manager.cli.etcd get method  

- src/ai/backend/gateway/config.py
- src/ai/backend/gateway/server.py
Detect app plugins through entrypoint, not by scanning modules in `BACKEND_EXTENSIONS`.
Users can disable installed app plugins through `--disable-plugins` cli option.
> Load app plugins through entrypoint

- src/ai/backend/gateway/config.py
- src/ai/backend/gateway/etcd.py
- tests/conftest.py
- tests/gateway/test_config.py
- tests/gateway/test_etcd.py
Pull request for #43.
- Get custom docker registry by `--docker-registry` option when starting gateway server.
- Save it into etcd config server when init.
> User provided docker registry

- src/ai/backend/gateway/etcd.py
For our enterprise customers, we now offer an additional service for managed Docker registry, which is served via [Harbor](https://goharbor.io).
Since [Harbor supports the official catalog API only for super-admin users](https://github.com/goharbor/harbor/issues/6784), we should implement a separate harbor-specific REST-based repository scanning routine for our `etcd rescan-images` implementation.
This PR adds support for the following per-registry etcd configs:
* `config/docker/registry/{registry-name}/type`: `docker` (default if not specified) or `harbor`
* `config/docker/registry/{registry-name}/project`: the project name used in Harbor
There is no change needed for existing registry configurations and everything should work as-is.
> Add support for harbor registry

- src/ai/backend/gateway/etcd.py
- src/ai/backend/gateway/resource.py
Add endpoints for watcher operations.
```
'GET',  '/watcher'
'POST', '/watcher/agent/start'
'POST', '/watcher/agent/stop'
'POST', '/watcher/agent/restart'
```
> APIs for agent watcher

- src/ai/backend/manager/models/user.py
Currently, keypair's `is_admin` is not dependent with user's role. This sometimes confuse admins, especially when they change user's role from user to admin. Even though the user is changed to admin, that account cannot perform admin operations since there is no admin keypair.
This pull-request updated keypair's `is_admin` field upon user role change.
```
if user's role -> admin/superadmin
make user's first keypair admin
if user's role -> non-admin
make user's first keypair user
if user have multiple active admin keypairs, inactivate them all
```
> Sync user keypair role

- src/ai/backend/gateway/auth.py
API endpoint which enables user can update password by "the" user. This API does not support updating other fields except password, at least for now. This should be differentiated with the GraphQL API for admins which can update all user-related fields for other users.
Added endpoint:
```
POST '/update-password' (old_password, new_password, new_password2)
```
> Add endpoint for updating user password

- setup.cfg
- src/ai/backend/gateway/auth.py
- src/ai/backend/manager/models/alembic/versions/0262e50e90e0_add_ssh_keypair_into_keypair.py
- src/ai/backend/manager/models/keypair.py
- src/ai/backend/manager/models/user.py
- src/ai/backend/manager/registry.py
Current SSH keypair used to connect to a container is created per container-basis. That means, user has to change private key for SSH/SFTP client, everytime a container is destroyed and created. Furthermore, when user spawns multiple containers and wants to connect to them alternately, the user has to change private key every time they connect to another container.
User can create `.ssh` virtual folder and store public key in `authorized_keys` to use the same private key. However, this method is not possible when group virtual folder is the only allowed type.
To ease the pain in those cases, this pull request supports per-keypair SSH keypair. When new keypair is created, manager automatically generates a new SSH keypair and saves them in DB (`keypairs.c.ssh_public_key` and …
> Keypair-specific SSH keypair

- src/ai/backend/gateway/etcd.py
- src/ai/backend/manager/models/image.py
Simple addition of `installed_agents` field in fetching images.
In client-side, there is a need to know which image is installed in which agents.
> Append agent ids when fetching image list

- src/ai/backend/gateway/dotfile.py
- src/ai/backend/gateway/exceptions.py
- src/ai/backend/gateway/server.py
- src/ai/backend/gateway/userconfig.py
- src/ai/backend/manager/models/alembic/versions/0262e50e90e0_add_ssh_keypair_into_keypair.py
- src/ai/backend/manager/models/alembic/versions/1e8531583e20_add_dotfile_column_to_keypairs.py
- src/ai/backend/manager/models/keypair.py
- src/ai/backend/manager/registry.py
This PR resolves issue lablup/backend.ai#98. 
- Added `dotfiles` column to `keypairs` table
- New `/dotfile` endpoint for basic CRUD operation of dotfiles
- `GET /dotfile`: Lists all available dotfiles per user
- `GET /dotfile?path=<SOMEPATH>`: Returns information of dotfile with given path
- `POST /dotfile`: Creates new dotfile 
- `PATCH /dotfile`: Updates dotfile with given patgh
- `DELETE /dotfile?path=<SOMEPATH>: Deletes dotfile from user with given path
- Manager now passes `dotfiles` list inside `internal_data` column to agent when creating kernel
> Implement dotfiles

- codecov.yml
- src/ai/backend/manager/models/agent.py
* When an agent starts up, there is a short period (a few seconds) that
the agent information is available in the manager database but the
live per-node statistics are not arrived yet.
* During this period, resolving a few node statistics fields in the
GraphQL's Agent schema results in a bogus HTTP 400 error.
* Let the manager report zero values when the statistics are not
available.
> Fix a bogus error due to missing livestat while agents starting up

- src/ai/backend/gateway/defs.py
- src/ai/backend/gateway/etcd.py
- src/ai/backend/manager/defs.py
- src/ai/backend/manager/registry.py
This PR is only for v19.12 (master).
* When there are mutually exclusive resource slot definitions such as
cuda.device and cuda.shares at the same time, any pending sessions
with one of those slots cannot be scheduled, because agents with both
slots do not exist but pending session requests are created with both
slots with the image's minimum required slots.
* Let the manager auto-fill the per-image minimum required resource slots
for intrinsic slots only (cpu and mem).
* This slightly breaks the backward compatibility for CLI users who
spawn GPU-acceleratored sessions, since they MUST SPECIFY either
cuda.device or cuda.shares EXPLICITLY ALWAYS.
> Auto-fill the minimum resource slots for intrinsic slots only

- src/ai/backend/manager/scheduler/fifo.py
- tests/manager/test_scheduler.py
Let's update the scheduler to favor CPU agents for session creation requests without accelerators.
But still, when CPU agents are full, those sessions must be scheduled on available GPU agents.
Internal ticket: OP#198
> Favor CPU agents for session creation requests without accelerators

- src/ai/backend/gateway/admin.py
- src/ai/backend/gateway/etcd.py
Previously, we have hard-coded the maximum number of docker image repositories fetched from the Docker Hub to 100. Now the number of our images (including non-kernel ones) has reached 94 with 60 kernels among them.
It's time to support proper pagination for the listing APIs, for Docker Hub, the vanilla Docker registry, and the Harbor instances.
Also, we need to warn explicitly if a seem-to-be-a-kernel image do not have `ai.backend.kernelspec` label, to prevent human mistakes when building new images.
> Support pagination for rescan-images

- src/ai/backend/gateway/etcd.py
This pull-request resolves https://github.com/lablup/backend.ai/issues/176.
Convert `yarl.URL` object to string before JSON response in fetching docker registry list.
> fix: error on fetching docker registry list

- src/ai/backend/gateway/vfolder.py
This pull request resolves an issue that a user folder cannot be created if `allowed_vfolder_hosts` is set only in the group-level (namely, host is not set in domain-/keypair-policy-level).
The cause of the problem is that the `allowed_vfolder_hosts` specified at the group level is not used when creating a user folder. Fixed to call `get_allowed_vfolder_hosts_by_user` instead of `get_allowed_vfolder_hosts_by_group` if there is no `group_id` parameter when creating a folder (meaning the request tries to create a user folder).
> fix: use get_allowed_vfolder_hosts_by_user when creating user folder

- changes/266.feature
- src/ai/backend/gateway/vfolder.py
Add an endpoint to rename a file or a directory inside a virtual folder.
`/vfolders/{vfolder-name}/rename_file`
- `target_path`: (`str`) path to a target file or directory
- `new_name`: (`str`) new name of the file
* If `target_path` does not exist, error will be returned.
* `new_name` should be a plain string, not a path like `/home/work/test.file`.
- It should be "rename", not "move" to a different directory.
* If there is already a file with `new_name`, error will be returned, not overwriting it.
> feat: API to rename file inside a virtual folder

- changes/270.fix
- src/ai/backend/manager/registry.py
NOTE: This restriction will be removed in 20.03 series.
> fix: Prevent destroying kernels in PREPARING/PULLING status

- changes/275.fix
- src/ai/backend/gateway/etcd.py
This PR fixes an issue where an unwanted value entered into an empty key ("") when settings Etcd configs with nested keys-values dictionary through `set_config`.
For example, when a client request to `POST /config/set` with following body,
```javascript
key: "resource"
value: {
"cpu": {
"min": "1"
},
"mem": {
"min": "256m"
}
}
```
actual keys/values in Etcd is filled like below.
```javascript
"resource": {
"cpu": {
"": "{'min': '1'}",
"min": "1"
},
"mem": {
"": "{'min': '256m'}",
"min": "256m"
}
}
```
> fix: remove unwanted nested dict empty key("")

- changes/286.feature
- src/ai/backend/gateway/auth.py
- src/ai/backend/gateway/exceptions.py
- src/ai/backend/gateway/server.py
- src/ai/backend/manager/plugin/__init__.py
- tests/conftest.py
- tests/gateway/test_auth.py
- tests/gateway/test_events.py
- tests/gateway/test_ratelimit.py
This PR executes `POST_SIGNUP` plugin hook after signup, to support user email validation through cloud plugin.
- Inactivate signup user's user/keypair if `CHECK_USER` handler returns `is_active = False`. 
- Separate out the logic to iterate available plugin hook handlers into `get_plugin_handler_by_type`.
This also fixed a bug which prevented registering webapp plugin handlers in 20.03. `etcd` and plugin webapps are registered before `runner.setup()` call. `runner.setup()` freezes `on_startup` event, which prevents appending sub apps in the `cleanup_context`.
> feat: execute POST_SIGNUP hook after sign up

- changes/288.feature
- src/ai/backend/gateway/vfolder.py
`update_shared_vfolder` now accepts `None` values for permission, which removes virtual folder permission for a specified user.
This PR implements one item specified in https://github.com/lablup/backend.ai/issues/150.
> feat: add a feature to kick off user who is shared virtual folder

- changes/299.breaking
- changes/299.fix
- src/ai/backend/gateway/manager.py
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/models/user.py
This PR fixes a bug which prevents fetching user information by user's uuid, raising following exception.
```
2020-07-11 22:07:59 ERROR graphql.execution.utils [5718] Traceback (most recent call last):                                                  │'type': <MountTypes.BIND: 'bind'>},
File "/home/adrysn/.pyenv/versions/venv-master-manager/lib/python3.8/site-packages/promise/promise.py", line 844, in handle_future_result    │{'opts': None,
resolve(future.result())                                                                                                                     │'permission': <MountPermission.READ_WRITE: 'rw'>,
File "/home/devops/backend.ai-master/manager/src/ai/backend/manager/models/base.py", line 439, in wrapped                                    │'source': …
```
> fix: convert user's uuid as str in key getter of fetching user by uuid

- changes/300.fix
- src/ai/backend/gateway/auth.py
- src/ai/backend/manager/models/base.py
- src/ai/backend/manager/models/resource_preset.py
This PR adds `context` for the call to `from_row` in `simple_db_mutate_returning_item`.
* During creation of resource preset which uses `simple_db_mutate_returning_item`, for example, it raises error stating `unexpected error: from_row() missing 1 required positional argument: 'row'`
* Minor un-related fix: return user's status in authorize API. This will be needed by client-side to determine the user's status and show better error texts when user fails to login.
> fix: add context for the call to from_row in simple_db_mutate_returning_item

- changes/302.feature
- src/ai/backend/manager/models/domain.py
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/models/group.py
- src/ai/backend/manager/models/user.py
This PR adds `purge` mutations to users, groups, and domains. Those three models did not expose delete operation until now (there is delete operation, but actually what it does is to just inactivate objects) since we thought it is too dangerous. However, there are requests for this feature from customers, and we decided to expose the API by `purge` mutation.
* Add `purge` mutation for domains.
- To purge a domain, there should be no bound groups and users.
* Add `purge` mutation for groups.
- There is no condition to purge a group since group is not an essential ingredient for users. When a group is deleted, users belong to it just lost access to that group, but their account still functions well if there are in other groups.
- Group's related virtual folders will also be purged together. …
> feat: add purge mutations for users, groups, and domains

- changes/306.fix
- src/ai/backend/manager/models/domain.py
- src/ai/backend/manager/models/group.py
- src/ai/backend/manager/models/user.py
Followup of https://github.com/lablup/backend.ai-manager/pull/302.
* Prevent purging a user when the user's virtual folders are mounted to some active sessions and/or the user has running sessions.
* Prevent purging a group when the group's virtual folders are mounted to some active sessions and/or the group has active sessions.
* Prevent purging a domain when it has active sessions.
> fix: prevent purging a user, group, and domain if bound resources are being used

- src/ai/backend/gateway/vfolder.py
Despite the tus client sends file size parameter as integer. The server encodes parameter file size in jwt as a string. This will ensure that the parameter when it is used is integer.
> fix: vfolder.py integer type cast to parameter size

- changes/0.breaking
- changes/312.breaking
- changes/312.feature
- config/sample.volume.json
- src/ai/backend/gateway/config.py
- src/ai/backend/gateway/etcd.py
- src/ai/backend/gateway/server.py
- src/ai/backend/gateway/vfolder.py
- src/ai/backend/manager/exceptions.py
- src/ai/backend/manager/models/storage.py
Support for the storage proxy and migrate existing vfolder operations/APIs to use the storage proxy
configured per vfolder host.
Public ticket: lablup/backend.ai#183, lablup/backend.ai#50
Internal ticket: OP#508
This work is also in conjunction with lablup/backend.ai-client-py#118 and lablup/backend.ai-client-js#17
This PR includes:
* A set of rewritten vfolder API implementations using storage proxies, via `manager.models.storage.StorageSessionManager`, with addition of a per-vfolder-host performance metric API.
* Bumped the major API version: `v6.20200815`
* A sample volume configuration for storage proxies in `config/sample.volume.json`
* Updated the etcd schema description in the `gateway.etcd` module.
> Storage Proxy

- changes/330.fix
- src/ai/backend/gateway/vfolder.py
This PR appends `recursive` parameter to deliver it to the storage proxy when deleting files.
> fix: hand over recursive parameter to storage proxy when delete_files

- changes/324.fix
- src/ai/backend/gateway/admin.py
When an exception is raised during handling of graphQL requests, there is currently no way to know why it occurred just by reading manager logs. This minor PR logs detailed error messages upon graphQL exceptions.
I initially thought that the exception logging should be handled in `GQLLoggingMiddleware`, but it seems like that the graphQL middlewares are called only after the requests are `resolve`d,  which failed to log exceptions for un-resolved requets.
> fix: log detailed error messages when there are graphQl exceptions

- changes/337.feature
- src/ai/backend/gateway/exceptions.py
- src/ai/backend/gateway/session.py
`get_task_logs` raises an error, so a client cannot get task logs in Backend.AI 20.09. This is due to the handler still uses deprecated etcd volume configs: `volumes/_mount` and `volumes/_fsprefix`. This PR removes them and build `log_path` variable correctly by fetching information from storage-proxy.
> fix: get_task_logs references deprecated etcd config

- changes/339.feature
- src/ai/backend/gateway/auth.py
This PR adds hooking point for `AUTHORIZE` with the `FIRST_COMPLETED` requirement.
* The hook accepts `params` and `dbpool` parameters. Especially, `dbpool` is needed to access DB from the hook.
* When any one of `AUTHORIZE` hook is passed, the `user` object returned by the hook is used .
* Thus, each `AUTHORIZE` hook should ensure that a corresponding Backend.AI account exists.
* For example, LDAP hook may perform the following jobs:
* Check if the user's login credential (email, password) passes the authentication from LDAP server.
* If not passed, just reject the request.
* If passed, ensure a Backend.AI account with the same email exists.
* If it does not exist, create a new Backend.AI account
* Return the existing or new `user` object.
* If there is no `AUTHORIZE` hook in the …
> feat: add hooking point for AUTHORIZE

- changes/340.fix
- src/ai/backend/gateway/auth.py
- src/ai/backend/gateway/vfolder.py
Check for already-invited users should use invitee emails, not requester email. This prevented a vfolder invited by two or more users.
> fix: unable to invite user to a vfolder, which is shared with another user

- changes/342.fix
- src/ai/backend/gateway/manager.py
- src/ai/backend/gateway/vfolder.py
This PR resolves https://github.com/lablup/backend.ai/issues/177.
`fetch_manager_status` references the value of Etcd's `nodes/manager`, which is deprecated from above 20.03 (https://github.com/lablup/backend.ai-manager/blob/master/src/ai/backend/gateway/etcd.py#L136). So, the request to fetch manager's status (`/status`) raises error, and this keeps clients from displaying the manager's status.
This PR has changed to use the key-value pair under `nodes/manager`, if there is no direct value of `nodes/manager`.
> fix: read manager ID from keys of etcd_info

- changes/350.fix
- src/ai/backend/manager/registry.py
After updating Backend.AI manager and agent, the compute plugins information is not updated unless we delete the agent information. The PR updates compute plugins inforamation when agent status is `ALIVE` as well.
> fix: update compute_plugins info from heartbeat for an ALIVE agent

- changes/377.fix
- setup.cfg
`aiodocker` is used int `registry.py`, but it is put in a test dependency. I think it should be a default dependency.
> fix: make aiodocker belong to prindipal dependencies

- changes/394.fix
- src/ai/backend/gateway/events.py
This PR removes b-prefix in sending server_closed due to innate code in "[aiohttp-sse](https://github.com/aio-libs/aiohttp-sse/blob/307fd35a84a66b7fb5adfd70cd5b7d709fa8508c/aiohttp_sse/__init__.py#L91)".
> fix: remove b-prefix in background task events function

- changes/401.feature
- src/ai/backend/manager/registry.py
Some users want to write a script which has different control flow depending on the launched kernel image.
> feat: add BACKENDAI_KERNEL_IMAGE environment variable in container

- changes/403.fix
- src/ai/backend/manager/scheduler/dispatcher.py
In some cases, sub containers are still RUNNING even though main container is TERMINATED, which we can call broken session. In this case, the scheduler for the scaling group which contains the broken session is unable to schedule PENDING sessions at all. To circumvent this edge case, we exclude broken sessions, that do not have main container, from fetching existing session list.
> fix: do not register sub containers to existing sessions if main container is TERMINATED

- changes/404.fix
- src/ai/backend/gateway/config.py
- src/ai/backend/manager/idle.py
`expire` parameter in aioredis's `set` method explicitly requires `int` type and `float` is not allowed.
> fix: idle_timeout was not working due to last_access save error

- changes/407.fix
- src/ai/backend/gateway/auth.py
- src/ai/backend/gateway/server.py
- src/ai/backend/manager/models/base.py
- src/ai/backend/manager/models/vfolder.py
This is a follow-up to #406, to keep the manager compatible with PostgreSQL v10 or older, where the JIT option is not available.
> fix: Add check for pgsql version to adjust connection args

- changes/419.feature
- src/ai/backend/manager/api/vfolder.py
- src/ai/backend/manager/models/vfolder.py
This PR adds API endpoints to share or unshare a group virtual folder to users directly with overriding permission. This is to allow specified users (usually teachers with user account) can upload data/materials to a group virtual folder while it is shared as read-only for all other group users (usually students).
Also, `query_accessible_vfolders` are refactored to account for the overriding permission of group virtual folders.
Only group virtual folders are directly sharable since user-type folders can be shared by invitation. Group folders are visible to every group users without user's choice, so it does not make sense to invite a group folder.
> feat: share group virtual folder directly without invitation

- changes/428.feature
- src/ai/backend/manager/scheduler/dispatcher.py
When loading the scheduler, it is to apply both the etcd setting and the current db setting.
this PR related to [#960](https://github.com/lablup/backend.ai-webui/issues/960) in webUI.
> feat:  unify global-default scheduler configs and per-scaling group scheduler options

- changes/436.fix
- setup.cfg
- src/ai/backend/manager/api/admin.py
- src/ai/backend/manager/models/agent.py
- src/ai/backend/manager/models/base.py
- src/ai/backend/manager/models/domain.py
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/models/group.py
- src/ai/backend/manager/models/kernel.py
- src/ai/backend/manager/models/keypair.py
- src/ai/backend/manager/models/resource_policy.py
- src/ai/backend/manager/models/resource_preset.py
- src/ai/backend/manager/models/scaling_group.py
- src/ai/backend/manager/models/user.py
- src/ai/backend/manager/models/utils.py
- src/ai/backend/manager/models/vfolder.py
* Just get the db connection whenever we need, instead of trying to
reuse a single connection across the whole query processing.
- The graphene and dataloader library tries to concurrently execute
nested async resolvers and this may cause "operation in progress"
DB API error in some queries.
* Refactor almost every mutation method using `simple_db_mutate()`
and `simple_db_mutate_with_returning_item()`, by adding pre_func
and post_func arguments to execute custom queries before/after
the main mutation query.
* Refactor existing mutation query preparation codes to better
utilize `set_if_set()` and other internal utilities.
> fix: Rewrite db connection mgmt for GraphQL resolvers and mutations

- changes/441.fix
- src/ai/backend/manager/idle.py
This PR adds logic not to collect data points for utilization idle checker when the current time does not exceed the sum of the last collect time and the `interval` of the checker. Previously, each Manager process independently collects data without considering the interval, which results in a much faster session termination than intended. 
For example, the idle timeout is reduced by half if there are two Managers since they collect the data twice within the configured interval. By the same logic, if there are three Managers, the idle timeout is reduced by one-third.
So, this PR logs the last collect time and does not collect the data when the `interval` is not passed from it.
> fix: do not collect data for utilization idle checker when interval is not passed

- changes/444.fix
- src/ai/backend/manager/scheduler/dispatcher.py
We are using PostgreSQL advisory locks to synchronize the scheduler invocation (both `PENDING` to `SCHEDULED` transition and `SCHEDULED` to `PENDING` transition).
The second transition usually takes more time due to agent RPC calls to create actual containers, and sometimes it results in database-level "lock not available" error (with `lock_timeout=30000` config).
Since the locking failure itself is not a bug, let's translate it to an informational log instead of alarming errors.
Though, we need to investigate potential deadlocks in the agent side if this happens frequently and repeatedly.
> fix: Handle failure of advisory locks gracefully

- changes/448.fix
- src/ai/backend/manager/api/admin.py
- src/ai/backend/manager/server.py
- fix: Add a new GQL handler that speaks standard-compliant responses
- fix: Bump the API version to indicate existence of the new GQL endpoint
> fix: Standard-compliant GQL endpoint

- changes/447.fix
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/registry.py
* It should be handled by the agent so that the execution should be
triggered and continued regardless of the manager-side interrupts
once the container creation succeeds in the agent.
> fix: Regression of batch-type sessions

- changes/451.fix
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/models/group.py
- src/ai/backend/manager/models/scaling_group.py
Without batching and with many number of projects, it may generate too many concurrent database connections at the same time when multiple `Group` GraphQL objects are queried with the `scaling_groups` field.
Let's apply the missing aiodataloader here.
> fix: Apply dataloader batching to Group.scaling_groups

- changes/452.feature
- changes/452.fix
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/models/group.py
* Add "group_by_name" query to get group(s) from their names.
* Remove potential spikes of concurrent transactions when querying
groups associated with specific users.
> fix: Revamp user group GQL queries

- changes/450.feature
- setup.cfg
- src/ai/backend/manager/config.py
- src/ai/backend/manager/server.py
This PR is started by https://op.lablup.ai/projects/backend-ai-server-and-sdk/work_packages/1414/
aiomonitor: https://github.com/aio-libs/aiomonitor
By using aiomonitor, you can monitoring asynchronous tasks and can execute some asynchronous commands in running application.
You can set port to connect with monitor by editing TOML configs.
> feat: Add aiomonitor for manager

- changes/454.feature
- src/ai/backend/manager/models/base.py
Add lock-related DB connection settings for better DB stability when the Manager does not release a lock and/or idle for a long time after acquiring a lock.
> feat: add lock-related DB connection settings

- changes/455.fix
- src/ai/backend/manager/scheduler/predicates.py
* There was a mistake while introducing DB transaction retries.
> fix: Regression of session concurrency limit checks

- changes/457.fix
- src/ai/backend/manager/models/group.py
- src/ai/backend/manager/models/scaling_group.py
* When fetching from a joined query and wanting to aggregate the rows by
the key only present in a joined source table, the column must be explicitly
selected in the base query.
> fix: A hidden bug in the new batched resolvers for Group and ScalingGroup

- changes/460.fix
- src/ai/backend/manager/idle.py
* Batch type sessions inherently do not have any interaction,
which is the criteria for idle timeout.
> fix: Let the timeout idle checker skip batch-type sessions

- changes/461.fix
- src/ai/backend/manager/api/session.py
Internal Ticket: OP#1432
This PR removes:
* Duplicate codes of checking the validity of `mount_map` argument.
This PR adds:
* Check duplicate alias folder name.
* Check existing folder name as alias name.
* Check empty alias name.
> fix: Fix duplicate codes and add duplicate target dir check for `mount_map` when creating sessions

- changes/475.feature
- config/sample.etcd.config.json
- src/ai/backend/manager/config.py
- src/ai/backend/manager/registry.py
Add an Etcd option to set MTU in creating an overlay network for a cluster session to support improved performance for multi-node cluster training.
Internal Ticket: OP#1458
Related PR: [webui#1120](https://github.com/lablup/backend.ai-webui/pull/1120)
> feat: Add Etcd option to set MTU for the overlay networks of a cluster session

- changes/474.feature
- src/ai/backend/manager/api/vfolder.py
This PR provides partial REST API for storage-proxy specific operations such as Quota. 
> ⚠️ &nbsp; NOTE: Not every REST API will be handled in this PR, only for the ones that have checked in the check-box below.
- Quota
> feature: provide extra operations for storage proxy

- changes/483.fix
- src/ai/backend/manager/models/utils.py
- src/ai/backend/manager/server.py
- tests/api/test_auth.py
- tests/conftest.py
- tests/test_advisory_lock.py
- tests/test_distributed.py
This is a follow-up of #482.
* Handle "lock not available" error upon shutdown.
* Use non-blocking `pg_try_advisory_lock()` instead of blocking `pg_advisory_lock()` to avoid conflicts with statement/lock timeout configurations.
- This incurs a slightly more CPU usage due to polling, but it will keep the DB client connection to be alive.
* refactor: Single-source database connection routines as `models.utils.connect_database()` async context manager.
> fix: Improve advisory locks (follow-up to #482)

- changes/485.feature
- src/ai/backend/manager/config.py
- src/ai/backend/manager/registry.py
The used etcd key is `config/network/rpc/keepalive-timeout` (default: 60 seconds).
Like Redis, the retry count is fixed to 3 times and the retry interval is calculated
from the given idle timeout with the minimum of 2 seconds.
> feat: Allow config of RPC keepalive timeout via etcd

- changes/487.fix
- src/ai/backend/manager/api/resource.py
After [the PR #482 to replace aioredlock with pg_advisory_lock](https://github.com/lablup/backend.ai-manager/pull/482), a client cannot get the response from session usage per period API endpoints (`/usage/xxx`). It is due to the `deferrable=True` option in starting DB transactions. The manager now opens a persistent DB transaction by #482, we should not set the `deferrable` option, which instructs to start the current transaction only after other ongoing transactions are all finished.
> fix: unable to get response from usage per period API

- changes/497.fix
- src/ai/backend/manager/registry.py
* This will increase overheads for individual RPC calls,
but may prevent hanging RPC call issues.
> fix: Remove reusable caching for RPC peer objects

- changes/502.fix
- src/ai/backend/manager/api/resource.py
This PR resolves the issue of sending empty responses by changing `rowcount` in query results to `len()` function in aggregating session usages,  since the query clause is `SELECT`.
Please refer to rowcount description at [sqlalchemy documentation](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=rowcount#sqlalchemy.engine.CursorResult.rowcount).
> fix: Regression of stats API after applying asyncpg

- changes/500.feature
- src/ai/backend/manager/models/agent.py
- src/ai/backend/manager/models/gql.py
This PR provides the mutation query of agent setting.
For now, the user with superadmin role can update `schedulable` value only.
Related PR: [backend.ai-webui#1167](https://github.com/lablup/backend.ai-webui/pull/1167).
> feat: add mutation query for agents table to update schedulable column

- changes/506.fix
- src/ai/backend/manager/models/kernel.py
- src/ai/backend/manager/registry.py
This pull request temporary solve the session_name matching problem (Too many sessions matched)
https://github.com/lablup/backend.ai/issues/297
> fix: Avoid TooManySessions error when there is an exact match, not only prefix matches

- changes/505.feature
- src/ai/backend/manager/api/session.py
This PR adds new rename_session API, as described on lablup/backend.ai#296.
> feat: Add support for session renaming

- changes/508.fix
- setup.cfg
- src/ai/backend/manager/defs.py
- src/ai/backend/manager/distributed.py
- src/ai/backend/manager/models/base.py
- tests/test_advisory_lock.py
This PR fixes new typecheck errors found by mypy 0.930 update.
> Update mypy to 0.930

- changes/504.feature
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/registry.py
- src/ai/backend/manager/scheduler/predicates.py
Resolve lablup/backend.ai/issues/308
* Move the check for "max-containers-per-session" of keypair resource policies from predicates to enqueueu_session of registry.py
* Regardless of the end of existing sessions , This check is determined by resource policy. 
* When the number of containers exceeds 'max_containers_per_session'
> feat: Move max_containers_per_session policy check from predicates

- changes/511.feature
- src/ai/backend/manager/models/agent.py
- src/ai/backend/manager/registry.py
Resolve: https://github.com/lablup/backend.ai/issues/317
Before DB update, It will call `update_scaling_group()` method of registry.py to update scaling group.
This PR can be merged after RPC method of agent is merged. 
https://github.com/lablup/backend.ai-agent/pull/327
> feat: Add mutation query for agents table to update scaling_group column

- changes/519.fix
- src/ai/backend/manager/api/wsproxy.py
In some rare cases, `TCPProxy` raises an `AttributeError` in proxying app requests like the image below.
This PR just explicitly declare the `down_task` attribute in the `TCPProxy` class to prevent the above issue.
> fix: declare down_task in TCPProxy to prevent AttributeError

- changes/522.fix.md
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/registry.py
- src/ai/backend/manager/scheduler/predicates.py
- fix: Apply nested transaction to `check_scaling_group` predicate
- fix: minor code clean up
- refactor: Remove legacy stat-sync codes and apply batching
- fix: Improve synchronization of kernel creation postprocessing
> fix: Reduce possibility of stuck in PREPARING under high-load conditions

- changes/525.fix.md
- setup.cfg
refs lablup/backend.ai#300
This will allow running Backend.AI Manager on Python 3.10.
> upstream: Migrate to aiodataloader-ng

- changes/515.feature
- changes/516.feature
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/defs.py
- src/ai/backend/manager/models/session_template.py
- tests/api/test_utils.py
Resolve: lablup/backend.ai#329
This is only about vfolder mount. Original functions of /home/work directory is not changed(logs, entrypoint, any other dotfiles).
Related PR:
lablup/backend.ai-agent#334 
lablup/backend.ai-webui#1194
lablup/backend.ai-client-py#204
**Test**
**Blacklist test**
> feat: arbitrary path vfolder mounts

- changes/531.fix
- src/ai/backend/manager/scheduler/dispatcher.py
This PR closes lablup/backend.ai#315, by forcing resource usage recalculation when session creation is failed.
> fix: occupied slot not released when session creation fails

- changes/517.fix
- src/ai/backend/manager/api/scaling_group.py
This PR fixes error where get_wsproxy_version API raising GenericNotFound error when user's current domain isn't associated with target scaling group.
> fix: get_wsproxy_version raising GenericNotFound

- changes/538.fix
- src/ai/backend/manager/api/scaling_group.py
This PR fixes issue `get_wsproxy_version` returning 404 when target scaling group is allowed to invididual keypair/user group rather than user's associated domain.
> fix: Let `get_wsproxy_version()` be aware of per-user/per-group scaling group mapping

- changes/530.fix
- src/ai/backend/manager/api/utils.py
Resolve: https://github.com/lablup/backend.ai/issues/358
Add query code when activated user is not found while remove user session.
> fix: admins cannot terminate inactivated user's compute sessions

- changes/542.fix
- src/ai/backend/manager/models/scaling_group.py
- src/ai/backend/manager/scheduler/predicates.py
- tests/test_predicates.py
This is a follow-up to lablup/backend.ai#343
Related with: lablup/backend.ai-webui#1190
**prevent allowed session types in empty and fix allowed session types check process handing**
- **Prevent allowed_session_types in empty status  using trafaret.**
Change it not to be empty to solve problem of If the scaling group's allowed_session_types is empty, predicate check fail failure.
- **Fix allowed_session_types check process handing**
Prevent stopping without checking all sgroups during the allowed_session_types check process
> fix: Don't allow empty values in allowed session types and scan all allowed scaling groups

- changes/553.fix
- src/ai/backend/manager/models/image.py
fix: lablup/backend.ai#393
follow-up-for: #541
SQLAlchemy connection: https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Connection
SQLAlchemy session: https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session
`Connection` is a functionality for DB-API, while `Session` can manage operations for ORM-mapped objects.
`Session` should be used when we want to use ORM functionalities.
> fix: Missing replacement of connection with session for ORM query

- changes/566.fix.md
- src/ai/backend/manager/api/etcd.py
- src/ai/backend/manager/api/resource.py
- src/ai/backend/manager/api/stream.py
refs lablup/backend.ai#383, lablup/backend.ai-comon#124
> fix: Type errors found with new etcd module

- changes/558.fix.md
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/registry.py
* No matterl the kernel creation in an agent succeeds or fails,
it should await all post creation tasks to either finalize or handle
errors.
* This has cuased sessions stuck at "PREPARING" status randomly
(with varied probability version by version) upon agent-side
kernel creation failures.
> fix: A long-standing, critical bug that leaked kernel creation tasks

- changes/559.fix
- src/ai/backend/manager/models/agent.py
- src/ai/backend/manager/models/alembic/versions/11146ba02235_change_char_col_to_str.py
alter table column type `agents.archtecture` from CHAR to String
> fix: Remove implicit trailing whitespace from the `agents.architecture` column

- changes/561.fix
- src/ai/backend/manager/api/resource.py
* The structure of the elements of `mounts` is changed from `list` to `str`, so we cannot access it as we did before 22.03.
* To make the contents of NFS value more useful, now it returns the physical host location of vfolders mounted, not just vfolder host, which was not so needed.
> fix: refer vfolder_mounts instead of will-be-deprecated mounts in returning session usage statistics

- changes/564.fix
- src/ai/backend/manager/api/session.py
Until 21.09, the `get_access_key_scope` function [checks the existence of the `owner_access_key` in the request parameter](https://github.com/lablup/backend.ai-manager/blob/57af21944cb7ebdf153ffc867b73c6c5658799a7/src/ai/backend/manager/api/utils.py#L57).
However, in 22.03, this check logic is somehow removed from the `get_access_key_scope`. This change prevented superadmins from querying other users' container logs or destroying them.
Perhaps, the responsibility of providing the parameter `owner_access_key` has moved to callers. So, this PR explicitly passes the `owner_access_key` to the `get_access_key_scope` function from two handlers: `destroy` and `get_container_logs`.
> fix: let admins destroy and get the logs of a session by passing owner's access key in determining the access scope

- changes/565.feature.md
- src/ai/backend/manager/cli/__main__.py
> Add Redis persistent DB mgmt commands when clearing history

- changes/569.fix
- src/ai/backend/manager/cli/image_impl.py
This PR removes unused `strict=True` parameters in `image_impl.py`'s method, which results some of `backend.ai image` commands fails to run.
> fix: remove invalid argument in `image_impl.py`

- changes/571.feature.md
- config/sample.toml
- setup.cfg
- src/ai/backend/manager/api/context.py
- src/ai/backend/manager/api/logs.py
- src/ai/backend/manager/cli/context.py
- src/ai/backend/manager/config.py
- src/ai/backend/manager/defs.py
- src/ai/backend/manager/idle.py
- src/ai/backend/manager/models/utils.py
- src/ai/backend/manager/pglock.py
- src/ai/backend/manager/scheduler/dispatcher.py
- src/ai/backend/manager/server.py
- src/ai/backend/manager/types.py
- tests/conftest.py
- tests/test_advisory_lock.py
- tests/test_scheduler.py
- fix: A bug in PgAdvisoryLock
- ci: Upgrade mypy to the latest version that supports Python 3.10
- feat: Implement replacible distributed lock backend
- feat: Set the default lock backend to "etcd"
> Replacible distributed lock backend

- changes/568.feature
- src/ai/backend/manager/models/base.py
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/models/image.py
This PR implements `clean_images` and `modify_image` mutations and fixes `b"` inserted before every `installed_agents`' element. 
- `clean_images`: removes image (and image aliases, of course) records from designated registry at database. Requires `registry` field. Only images from this registry will be removed.
- `modify_image`: update image metadata records on database. Check `ModifyImageInput` inside `image.py` for supported fields.
> feat: implement image metadata related GraphQL mutations

- changes/574.fix
- src/ai/backend/manager/registry.py
This PR fixes `occupied_slots` column on `agents` table not matching to actual resource occupied on corresponding agent when fractional resource requested is rounded down to quantum size when creating kernel on agent.
> fix: rounded down resource not released after kernel creation

- changes/576.fix
- src/ai/backend/manager/api/stream.py
Getting Redis local time in every streaming proxy request will quickly deplete the Redis connection pool. This was fixed by https://github.com/lablup/backend.ai-manager/pull/526, but reintroduced by https://github.com/lablup/backend.ai-manager/pull/533 by merge mistake.
This PR removes the duplicated logic to suppress the depletion of the Redis connection pool.
> fix: remove duplicated logic to obtain redis local time in streaming proxy requests

- changes/577.fix
- src/ai/backend/manager/api/resource.py
- List every needed columns in querying kernels information.
- Look up the `last_stat` first and falls back to the `raw_stat` from Redis.
- Change the location of NVIDI GPU's smp and allocated memory stats in the `last_stat`.
> fix: regression of the logic in getting the container stats per period

- changes/580.fix.md
- src/ai/backend/manager/registry.py
a method `sync_kernel_stats` in ai.backend.manager.registry.AgentRegistry, `per_kernel_updates` is used to bind update query parameters.
`per_kernel_updates` can be empty but it tries query the update with no binded parameter.
> fix: do not query update where update is empty

- changes/583.feature.md
- fixtures/example-keypairs.json
- src/ai/backend/manager/api/context.py
- src/ai/backend/manager/api/stream.py
- src/ai/backend/manager/config.py
- src/ai/backend/manager/idle.py
- src/ai/backend/manager/models/alembic/versions/81c264528f20_add_max_session_lifetime.py
- src/ai/backend/manager/models/resource_policy.py
- src/ai/backend/manager/scheduler/dispatcher.py
- src/ai/backend/manager/server.py
resolves lablup/backend.ai-internal#46
> feat: Add `KeyPairResourcePolicy.max_session_lifetime`

- changes/589.fix
- src/ai/backend/manager/api/session.py
this PR resolves https://github.com/lablup/backend.ai/issues/420
- `params['VARIABLE_NAME']` -> `params.get('VARIABLE_NAME')`
- Change default value  for `callback_url` and `startup_command` to None in `create_from_template()` like `create_from_params()`.
> fix: changes the default values of session options.

- changes/592.fix.md
- config/sample.toml
- src/ai/backend/manager/config.py
In our internal testing, etcetra-based distributed lock seems to malfunction when spurious lock timeouts.
Until we find and fix the root cause, temporarily fallback to the prior implementation.
(This is why I've made it as a configurable option!)
> fix: Temporarily rollback the default distributed lock impl.

- changes/591.feature
- src/ai/backend/manager/api/exceptions.py
- src/ai/backend/manager/api/session.py
Apply to wrap UnknownImageReference
1. Define `UnknownImageReferenceError` exception
error_type: 'https://api.backend.ai/probs/unknown-image-reference-error'
error_title: 'Unknown Image Reference'
2. Apply to wrap `UnknownImageReference` as `ObjectNotFound` instead of `InternalServerError`
refs:
- lablup/backend.ai#392
- lablup/backend.ai#378
> refactor: wrap `UnknownImageReference` as `ObjectNotFound`

- changes/593.fix
- src/ai/backend/manager/pglock.py
- src/ai/backend/manager/types.py
Current version raises an exception when running `ai.backend.manager.server`:
```zsh
manager % python -m ai.backend.manager.server --debug
File "/Users/rapsealk/Desktop/git/backend.ai/backend.ai-dev/manager/src/ai/backend/manager/pglock.py", line 5, in <module>
from ai.backend.common.distributed import AbstractDistributedLock
ImportError: cannot import name 'AbstractDistributedLock' from 'ai.backend.common.distributed' (/Users/rapsealk/Desktop/git/backend.ai/backend.ai-dev/common/src/ai/backend/common/distributed.py)
```
I found that the code to define `AbstractDistributedLock` has moved from `ai.backend.common.distributed` to `ai.backend.common.lock` after commit https://github.com/lablup/backend.ai-common/commit/8aafb0db8d13289f8f12049e8edcb67c3fc60007, but `ai.backend.manager.pglock` …
> fix: Update `AbstractDistributedLock` import path
