- src/ai/backend/gateway/exceptions.py
- src/ai/backend/gateway/kernel.py
- src/ai/backend/gateway/vfolder.py
- tests/conftest.py
- tests/gateway/test_vfolder.py
Pull request for #91.
* Add a new logic to decide folder_host
* Change the logic to check duplicate vfolders
> General vfolder host

- alembic/versions/0e558d06e0e3_add_service_ports.py
- src/ai/backend/gateway/exceptions.py
- src/ai/backend/gateway/kernel.py
- src/ai/backend/gateway/stream.py
- src/ai/backend/gateway/wsproxy.py
- src/ai/backend/manager/models/kernel.py
- src/ai/backend/manager/registry.py
> Service Ports for App Streaming

- setup.cfg
- src/ai/backend/gateway/config.py
- src/ai/backend/gateway/vfolder.py
> Add APIs for token based download.

- src/ai/backend/manager/models/user.py
User's domain name can be updated now.
> Let user domain can be updated by superadmin

- src/ai/backend/gateway/etcd.py
- src/ai/backend/manager/registry.py
refs lablup/backend.ai-agent#153 (→ lablup/backend.ai-agent#154) and lablup/backend.ai-console#157.
> Implement auto-pull option stored in etcd

- src/ai/backend/gateway/kernel.py
- src/ai/backend/gateway/stream.py
- src/ai/backend/manager/registry.py
This PR adds new `extrainfo` endpoint to stream API.
Check lablup/backend.ai-agent#152 and lablup/backend.ai#54 for more details.
> Add support for handing service url template

- .gitignore
- src/ai/backend/gateway/kernel.py
- src/ai/backend/gateway/server.py
- src/ai/backend/manager/models/alembic/versions/d452bacd085c_add_mount_map_column_to_kernel.py
- src/ai/backend/manager/models/kernel.py
- src/ai/backend/manager/registry.py
- src/ai/backend/manager/scheduler.py
This PR resolves lablup/backend.ai#69 . 
What has changed:
- New API version `v4.20191119` created, which reflects new `mount_map` property when creating kernel.
- New JSONB column `mount_map` added to `kernel` table on alembic.
- Kernel API now accepts `mount_map` property inside `creation_config`.
> mount vFolder on a custom location

- requirements-ci.txt
- src/ai/backend/gateway/etcd.py
- src/ai/backend/gateway/resource.py
- src/ai/backend/manager/registry.py
> Unified resource slots

- codecov.yml
- setup.cfg
- src/ai/backend/gateway/etcd.py
- src/ai/backend/gateway/events.py
- src/ai/backend/gateway/manager.py
- src/ai/backend/gateway/server.py
- src/ai/backend/gateway/typing.py
- src/ai/backend/manager/cli/etcd.py
- src/ai/backend/manager/models/base.py
- src/ai/backend/manager/models/kernel.py
- tests/conftest.py
- tests/gateway/test_auth.py
- tests/gateway/test_events.py
- tests/gateway/test_ratelimit.py
- tests/manager/test_registry.py
* Update the package dependencies to the latest ones.
* Update the code and tests to run in Python 3.8.1 (it is broken after this minor patch upgrade....)
* Make it easier to write unit tests for now and the future.
> Refactoring for better unit tests

- setup.cfg
[https://github.com/lablup/backend.ai/issues/35](#35)
Entrypoint for unified cli.
@achimnol
> Added entrypoint and removed old scripts

- setup.cfg
- src/ai/backend/gateway/config.py
- src/ai/backend/gateway/vfolder.py
This is a hotfix to keep all vfolder (i.e., NFS) operations async.
refs lablup/backend.ai#102
> Make all vfolder operations to be async

- src/ai/backend/gateway/vfolder.py
This is the fix for lablup/backend.ai#106
Previous feature branch was deleted due to having irrelevant commits in there.
> Make tus upload asynchronous

- src/ai/backend/manager/registry.py
- tests/manager/test_registry.py
This is also a demonstration of how to mock a complicated function including Redis and aiopg accesses.
Ticket: OP#142
> Fix missing agents.addr updates for heartbeats

- src/ai/backend/gateway/vfolder.py
Partial fix for lablup/backend.ai#158. Fixed the download error, no change on trafaret validation error yet.
> Fix for the download from console error.

- src/ai/backend/manager/scheduler.py
This is the backport of #241 for v19.09 series.
Internal ticket: OP#198
> Backport: Favor CPU agents for session request without accelerators

- setup.cfg
- src/ai/backend/gateway/events.py
- src/ai/backend/gateway/session.py
- src/ai/backend/gateway/typing.py
- src/ai/backend/gateway/utils.py
- src/ai/backend/gateway/vfolder.py
Manager part for lablup/backend.ai#102. Using AsyncFileWriter context manager for the sequential asynchronous writes.
> Apply AsyncFileWriter on the manager side

- .github/workflows/lint-flake8.yml
- .github/workflows/typecheck-mypy.yml
- src/ai/backend/gateway/config.py
- src/ai/backend/gateway/server.py
- src/ai/backend/manager/cli/etcd.py
- tests/conftest.py
Let's make it easier to distinguish the source of configurations and share the reusable IVs.
> Refactor configs

- src/ai/backend/gateway/vfolder.py
This PR restricts the creation for folders that already exist.
> Restrict Creating directory already exists

- CHANGELOG.rst
- src/ai/backend/gateway/kernel.py
- src/ai/backend/gateway/resource.py
- src/ai/backend/manager/registry.py
Let's add a programmatic, automated way that does what we do for manual agent recovery.
> Support for forced termination of sessions

- src/ai/backend/gateway/session.py
This PR fixes simple parameter checking routine.
> Fix wrong parameter check routine for trafaret

- src/ai/backend/gateway/exceptions.py
- src/ai/backend/gateway/session.py
- src/ai/backend/manager/models/alembic/versions/f5530eccf202_add_kernels_uuid_prefix_index.py
- src/ai/backend/manager/registry.py
> Accept session UUIDs and their prefixes in addition to client-specified IDs (names)

- changes/264.fix
- src/ai/backend/gateway/logs.py
- src/ai/backend/manager/models/vfolder.py
`mark_read` is Bool type, so do not have `lower` method.
> fix: error fetching server error logs

- changes/269.feature
- setup.cfg
- src/ai/backend/gateway/resource.py
- src/ai/backend/manager/models/kernel.py
- src/ai/backend/manager/registry.py
> Exclude TERMINATING status from user resource accounting

- src/ai/backend/gateway/server.py
- src/ai/backend/gateway/session.py
- src/ai/backend/gateway/stream.py
- src/ai/backend/manager/plugin/error_monitor.py
Follow-up of #315 and #316.
- Updated type annotation of context_env in capture_exception
> Fix error monitor plugin inheritance

- changes/319.feature
- scripts/migrate-vfolder-structure.py
Script to migrate the vfolder vroot/local structure.
Example usage: python migrate-vfolder-structure.py /Users/name/vroot/local/ /Users/name/vroot/vfs/
This script will automatically create new folder structure and move files.
> script migrate vfolder structure

- changes/317.feature
- src/ai/backend/gateway/vfolder.py
Implemented the second functionality listed in issue lablup/backend.ai#150.
> Feature: Add functionality for the user to leave a shared vfolder

- changes/354.fix
- src/ai/backend/gateway/etcd.py
- src/ai/backend/gateway/resource.py
- src/ai/backend/gateway/vfolder.py
- src/ai/backend/manager/models/group.py
- src/ai/backend/manager/models/image.py
- src/ai/backend/manager/models/user.py
This PR is for replacing config_server, which is legacy code to shared_config.
> fix: replace config_server legacy code to shared_config

- changes/352.fix
- src/ai/backend/gateway/exceptions.py
- src/ai/backend/gateway/vfolder.py
After merging the PR,
uncaught error due to folder related operation failed will be covered by proper exception message.
> fix: wrap storage manager request with try-exception block

- changes/357.feature
- src/ai/backend/gateway/config.py
- src/ai/backend/manager/cli/__main__.py
- src/ai/backend/manager/cli/etcd.py
- src/ai/backend/manager/container_registry/__init__.py
- src/ai/backend/manager/container_registry/base.py
- src/ai/backend/manager/container_registry/docker.py
- src/ai/backend/manager/container_registry/harbor.py
- tests/conftest.py
> Rewrite container registry support

- changes/369.fix
- src/ai/backend/manager/registry.py
This is an adapation of #368 for the 20.03 branch
> fix: Race condition of kernel status update during kernel creation

- changes/395.fix
- src/ai/backend/gateway/cluster_template.py
- src/ai/backend/gateway/config.py
- src/ai/backend/gateway/session_template.py
> fix: Explicitly use yaml.safe_load()

- changes/393.feature
- src/ai/backend/gateway/vfolder.py
This PR simply updates Vfolder queries by appending the parameter ``cloneable``, which is related to cloning and updating options in Vfolder.
> add: Append cloneable parameter for Vfolder cloning and updating options

- changes/397.feature
- src/ai/backend/gateway/vfolder.py
This PR provides to rename directories in Vfolder.
> feat: support renaming directories in vfolder

- changes/437.feature
- src/ai/backend/manager/registry.py
This PR adds each user's own access key as an environment variable called 'BACKENDAI_ACCESS_KEY'.
> feat: add access key into environment

- changes/439.fix
- src/ai/backend/manager/plugin/error_monitor.py
- src/ai/backend/manager/server.py
refs lablup/backend.ai#268
* Let's handle missing root context gracefully but with explicit warning.
This may indicate a configuration/installation error.
> fix: Initialization of error monitor plugin

- setup.cfg
lablup/backend.ai#253
Change setup.cfg to make the manager be able to use the PyJWT v2.
> feat: update PyJWT to v2 series

- changes/443.feature
- src/ai/backend/manager/registry.py
- tests/test_registry.py
lablup/backend.ai#270
Make a error message when raise IntegrityError due to missing scaling groups.
> feat: Add a human readable error message for missing scaling groups

- changes/453.fix
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/models/kernel.py
- src/ai/backend/manager/models/keypair.py
- src/ai/backend/manager/models/minilang/ordering.py
- src/ai/backend/manager/models/storage.py
> fix: Missing GQL root query field updates

- changes/486.fix
- src/ai/backend/manager/config.py
this commit fixes lablup/backend.ai#293.
> Fix: Ignore malformed image when listing available images

- changes/495.fix
- src/ai/backend/manager/api/events.py
- src/ai/backend/manager/models/keypair.py
- fix: Use proper txn isolation levels for session/kernel event subscribers
- fix: Use proper txn isolation level when querying user info
> fix: Improve session/kernel event notification stability

- changes/496.fix
- setup.cfg
- src/ai/backend/manager/api/admin.py
- src/ai/backend/manager/api/auth.py
- src/ai/backend/manager/api/etcd.py
- src/ai/backend/manager/api/manager.py
- src/ai/backend/manager/api/resource.py
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/api/vfolder.py
- src/ai/backend/manager/background.py
- src/ai/backend/manager/server.py
https://docs.aiohttp.org/en/stable/changes.html
> setup: Upgrade aiohttp to 3.8

- changes/509.fix
- src/ai/backend/manager/api/events.py
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/api/stream.py
- src/ai/backend/manager/api/types.py
- src/ai/backend/manager/api/wsproxy.py
- src/ai/backend/manager/background.py
- src/ai/backend/manager/config.py
- src/ai/backend/manager/idle.py
- src/ai/backend/manager/models/domain.py
- src/ai/backend/manager/models/group.py
- src/ai/backend/manager/registry.py
- src/ai/backend/manager/scheduler/dispatcher.py
- src/ai/backend/manager/server.py
- tests/api/test_auth.py
This PR fixes typing issues found by pyright, though we are not going to include pyright in CI yet.
> fix: Update typing using pyright

- changes/510.fix.md
- src/ai/backend/manager/distributed.py
- src/ai/backend/manager/scheduler/dispatcher.py
- src/ai/backend/manager/server.py
- tests/test_distributed.py
* fix: Close the aiomonitor session later to debug shutdown hangs better
> Fix potential hang-up issues while shutting down the service

- .github/workflows/default.yml
- changes/520.feature
- changes/520.misc
- requirements/lint.txt
- requirements/test.txt
- requirements/typecheck.txt
Modify following files to add backend.ai-cli module dependency when test push or pull request.
* .github/workflows/default.yml
* requirements/lint.txt
* requirements/test.txt
* requirements/typecheck.txt
> ci: Install the matching branch of backend.ai-cli

- changes/533.feature
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/api/stream.py
- src/ai/backend/manager/api/wsproxy.py
* Wrap create_task under asyncio.shield to control when async job is finished
* Use aiotools.Timer to make a stats report
* Related to https://github.com/lablup/backend.ai/issues/359
> fix: Ensure shutdown cancellation of shielded async tasks

- changes/548.feature.md
- src/ai/backend/manager/api/vfolder.py
- src/ai/backend/manager/models/storage.py
> feat: Add vfolder move-file API

- changes/563.fix
- src/ai/backend/manager/registry.py
prevent doing `mset()` to redis if the given Map is empty.
> Do not `MSET` with empty updates in `recalculate_usage()`

- MIGRATION.md
- changes/566.misc.md
Add a migration guide as 22.03 changes many things about databases.
This PR will be kept open until we finalize the release.
> Add MIGRATION.md

- changes/581.fix.md
- src/ai/backend/manager/api/auth.py
- src/ai/backend/manager/api/events.py
- src/ai/backend/manager/api/exceptions.py
- src/ai/backend/manager/api/scaling_group.py
- src/ai/backend/manager/api/session.py
- src/ai/backend/manager/api/vfolder.py
- src/ai/backend/manager/models/gql.py
- src/ai/backend/manager/server.py
> refactor: Separate use cases of URLNotFound and ObjectNotFound

- changes/582.fix.md
- src/ai/backend/manager/api/exceptions.py
refs lablup/backend.ai#378, follow-up to #581
> refactor: Inherit ObjectNotFound errors

- changes/584.fix
- src/ai/backend/manager/registry.py
This PR closes https://github.com/lablup/backend.ai-internal/issues/50.
> fix: do not create a session when memory is not larger than shared memory

- changes/585.feature
- src/ai/backend/manager/api/vfolder.py
- src/ai/backend/manager/models/vfolder.py
- fix: https://github.com/lablup/backend.ai/issues/419
- related PR: https://github.com/lablup/backend.ai-webui/pull/1290
> Include `group_id` params when getting allowed vfolder hosts

- changes/588.fix
- src/ai/backend/manager/models/vfolder.py
This PR resolves the issue raised on [backend.ai-webui#1302](https://github.com/lablup/backend.ai-webui/issues/1302).
> fix: add automount folder when session creation occurs
